# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57f5f1923a14f32c0b12d0e2d874e1a0ef75594d22902c217363d800591f2ac38a7d2748100c25d63dd96bc8eea06666871e8e5b41a723da8b7cbe60928225af

test:
  secret_key_base: 73d061a3a6b3c24efb1fbadbb6b3e124a647bf914672d4ecdb4e9a129f94415d4b1f4fd81a1d368851142c5e67a44a1d6f4469f0c5669371d2a8aa6a86ca7669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
